sudo: false
language: python

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - clang-3.5
            - clang-format-3.6
            - libatlas-base-dev

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then PYTHON=python; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then $PYTHON -m pip install pythran-openblas; fi
    - $PYTHON -m pip install --upgrade pip setuptools wheel six cython
    - $PYTHON -m pip install --only-binary=numpy,scipy -U ply "networkx>=2" colorlog numpy scipy "pytest==5.3.5" pytest-xdist gast ipython nbval
    - $PYTHON setup.py install 1> /dev/null

python:
    - "3.8"

matrix:
    include:
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS=-g TESTCASE='pythran/tests/test_[ab]*.py pythran/tests/test_c[b-z]*.py pythran/tests/test_numpy_[a-eg-r]*.py pythran/tests/test_numpy_f[a-t]*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS="-DUSE_XSIMD -march=native" TESTCASE='pythran/tests/test_[ab]*.py pythran/tests/test_c[b-z]*.py pythran/tests/test_numpy_[a-eg-r]*.py pythran/tests/test_numpy_f[a-t]*.py'
        - env: CC=gcc-5 CXX=g++-5 CXXFLAGS="-fopenmp" TESTCASE='pythran/tests/test_[ab]*.py pythran/tests/test_c[b-z]*.py pythran/tests/test_numpy_[a-eg-r]*.py pythran/tests/test_numpy_f[a-t]*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS=-g TESTCASE='pythran/tests/test_ca*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS="-DUSE_XSIMD -march=native" TESTCASE='pythran/tests/test_ca*.py'
        - env: CC=gcc-5 CXX=g++-5 CXXFLAGS="-fopenmp" TESTCASE='pythran/tests/test_ca*.py'
        - env: CC=gcc-5 CXX=g++-5 CXXFLAGS="-DUSE_XSIMD -march=native -fopenmp" TESTCASE='pythran/tests/test_ca*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS=-g TESTCASE='pythran/tests/test_[d-m]*.py pythran/tests/test_n[a-t]*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS="-DUSE_XSIMD -march=native" TESTCASE='pythran/tests/test_[d-m]*.py pythran/tests/test_n[a-t]*.py'
        - env: CC=gcc-5 CXX=g++-5 CXXFLAGS="-fopenmp" TESTCASE='pythran/tests/test_[d-m]*.py pythran/tests/test_n[a-t]*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS=-g TESTCASE='pythran/tests/test_numpy_f[u-z]*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS="-DUSE_XSIMD -march=native" TESTCASE='pythran/tests/test_numpy_f[u-z]*.py'
        - env: CC=gcc-5 CXX=g++-5 CXXFLAGS="-fopenmp" TESTCASE='pythran/tests/test_numpy_f[u-z]*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS=-g TESTCASE='pythran/tests/test_numpy_[s-z]*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS="-DUSE_XSIMD -march=native" TESTCASE='pythran/tests/test_numpy_[s-z]*.py'
        - env: CC=gcc-5 CXX=g++-5 CXXFLAGS="-fopenmp" TESTCASE='pythran/tests/test_numpy_[s-z]*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS=-g TESTCASE='pythran/tests/test_[o-w]*.py'
        - env: CC=clang-3.5 CXX=clang++-3.5 CXXFLAGS="-DUSE_XSIMD -march=native" TESTCASE='pythran/tests/test_[o-w]*.py'
        - env: CC=gcc-5 CXX=g++-5 CXXFLAGS="-fopenmp" TESTCASE='pythran/tests/test_[o]*.py'
        - env: CC=gcc-5 CXX=g++-5 CXXFLAGS="-fopenmp" TESTCASE='pythran/tests/test_[p-w]*.py'
        - env: PYTHRAN_DOC=true
        - env: PYTHONOPTIMIZE=0 CC=gcc-5 CXX=g++-5 TESTCASE='pythran/tests/test_ca*.py'
        - env: PYTHONOPTIMIZE=1 CC=gcc-5 CXX=g++-5 TESTCASE='pythran/tests/test_ca*.py'
        - env: PYTHONOPTIMIZE=2 CC=gcc-5 CXX=g++-5 TESTCASE='pythran/tests/test_ca*.py'

        - os: osx
          language: generic
          env: PYTHON=python3


script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh ./pythran/tests/travis_test.sh ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then printf '[compiler]\nblas=pythran-openblas\n' > ~/.pythranrc ; $PYTHON -m pytest pythran/tests/test_base.py pythran/tests/test_advanced.py ; fi
